### PR TITLE
port the driver patch to linux-yocto-4.8.

### PR DESCRIPTION
**Pull request by ipuustin**
There isn't much to be ported, but the line numbers change a bit.

### CODE REVIEW

**Comment by ipuustin** [comment]
Anyone want to review this patch? This is needed for using RealSense cameras on systems based on linux-yocto 4.8. The patch itself is almost the same as the linux-yocto 4.4 patch, only the line numbers change a bit.

**Comment by niryk** [comment]
@ev-mp , @dorodnic please confirm this change

**Comment by ev-mp** [comment]
The patch update seem legit.
but switching to completely different Kernel mean that we need to rerun LibRealSense full validation cycle for Ostro.

**Comment by ipuustin** [comment]
Well, the patch just adds support for a different kernel. It doesn't remove support for kernel 4.4. If your validation target is still running 4.4 then nothing would change there. I don't see a reason for a full validation cycle for any target that uses kernel 4.4 with the old patch.

**Comment by mattcurfman** [comment]
Merged PR to ostro branch.  Welcome new PR if required for master or morty branch also.

**Pull request merged**
